### ISSUE TITLE
[Source]: Epic

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-sources#76]
### EHR/Platform Name

Epic

### CHPL Website

https://chpl.healthit.gov/#/listing/11304

### Developer Documentation

https://fhir.epic.com/Documentation?docId=developerguidelines

### Endpoint List

https://open.epic.com/MyApps/Endpoints

### Developer Portal

https://open.epic.com/

### Sandbox Patient Credentials

https://fhir.epic.com/Documentation?docId=testpatients

### Platform Developer Readiness Checklist

- [X] developer documentation
- [X] sandbox - endpoint published
- [X] sandbox - client registration
- [X] sandbox - test patient username & password
- [X] sandbox - no fees
- [X] sandbox - [inferno testing](https://inferno.healthit.gov/suites/g10_certification) passed
- [X] production - client registration
- [X] production - endpoint list published
- [X] production - endpoint catalog/health system info published
- [X] production - no fees
- [X] production - automatic client distribution
